#!/usr/bin/env python
# __author__ = "Ronie Martinez"
# __copyright__ = "Copyright 2018-2020, Ronie Martinez"
# __credits__ = ["Ronie Martinez"]
# __maintainer__ = "Ronie Martinez"
# __email__ = "ronmarti18@gmail.com"
import string

import pytest

from latex2mathml.tokenizer import tokenize

PARAMS = [
    ("single backslash", "\\", ["\\"]),
    ("alphabets", string.ascii_letters, list(string.ascii_letters)),
    ("numbers", string.digits, [string.digits]),
    ("backslash after number", "123\\", ["123", "\\"]),
    ("double backslash after number", r"123\\", ["123", r"\\"]),
    ("decimal", "12.56", ["12.56"]),
    ("incomplete decimal", r"12.\\", ["12", ".", r"\\"]),
    ("numbers and alphabets", "5x", list("5x")),
    ("decimals and alphabets", "5.8x", ["5.8", "x"]),
    ("string with spaces", "3 x", ["3", "x"]),
    ("operators", "+-*/=()[]_^{}", list("+-*/=()[]_^{}")),
    (
        "numbers, alphabets and operators",
        "3 + 5x - 5y = 7",
        ["3", "+", "5", "x", "-", "5", "y", "=", "7"],
    ),
    ("symbols", r"\alpha\beta", [r"\alpha", r"\beta"]),
    ("symbols appended with number", r"\frac2x", [r"\frac", "2", "x"]),
    (
        "matrix",
        r"\begin{matrix}a & b \\ c & d \end{matrix}",
        [r"\begin{matrix}", "a", "&", "b", r"\\", "c", "&", "d", r"\end{matrix}"],
    ),
    (
        "matrix with alignment",
        r"\begin{matrix*}[r]a & b \\ c & d \end{matrix*}",
        [
            r"\begin{matrix*}",
            "[",
            "r",
            "]",
            "a",
            "&",
            "b",
            r"\\",
            "c",
            "&",
            "d",
            r"\end{matrix*}",
        ],
    ),
    (
        "matrix with negative sign",
        r"\begin{matrix}-a & b \\ c & d \end{matrix}",
        [r"\begin{matrix}", "-", "a", "&", "b", r"\\", "c", "&", "d", r"\end{matrix}"],
    ),
    (
        "simple array",
        r"\begin{array}{cc} 1 & 2 \\ 3 & 4 \end{array}",
        [
            r"\begin{array}",
            "{",
            "c",
            "c",
            "}",
            "1",
            "&",
            "2",
            r"\\",
            "3",
            "&",
            "4",
            r"\end{array}",
        ],
    ),
    ("subscript", "a_{2,n}", ["a", "_", "{", "2", ",", "n", "}"]),
    (
        "superscript with curly braces",
        "a^{i+1}_3",
        ["a", "^", "{", "i", "+", "1", "}", "_", "3"],
    ),
    (
        "issue #33",
        r"""\begin{bmatrix}
     a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
     a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
     \vdots  & \vdots  & \ddots & \vdots  \\
     a_{m,1} & a_{m,2} & \cdots & a_{m,n}
    \end{bmatrix}""",
        [
            r"\begin{bmatrix}",
            "a",
            "_",
            "{",
            "1",
            ",",
            "1",
            "}",
            "&",
            "a",
            "_",
            "{",
            "1",
            ",",
            "2",
            "}",
            "&",
            r"\cdots",
            "&",
            "a",
            "_",
            "{",
            "1",
            ",",
            "n",
            "}",
            r"\\",
            "a",
            "_",
            "{",
            "2",
            ",",
            "1",
            "}",
            "&",
            "a",
            "_",
            "{",
            "2",
            ",",
            "2",
            "}",
            "&",
            r"\cdots",
            "&",
            "a",
            "_",
            "{",
            "2",
            ",",
            "n",
            "}",
            r"\\",
            r"\vdots",
            "&",
            r"\vdots",
            "&",
            r"\ddots",
            "&",
            r"\vdots",
            r"\\",
            "a",
            "_",
            "{",
            "m",
            ",",
            "1",
            "}",
            "&",
            "a",
            "_",
            "{",
            "m",
            ",",
            "2",
            "}",
            "&",
            r"\cdots",
            "&",
            "a",
            "_",
            "{",
            "m",
            ",",
            "n",
            "}",
            r"\end{bmatrix}",
        ],
    ),
    ("issue #51", r"\mathbb{R}", ["&#x0211D;"]),
    (
        "issue #55",
        r"\begin{array}{rcl}ABC&=&a\\A&=&abc\end{array}",
        [
            r"\begin{array}",
            "{",
            "r",
            "c",
            "l",
            "}",
            "A",
            "B",
            "C",
            "&",
            "=",
            "&",
            "a",
            r"\\",
            "A",
            "&",
            "=",
            "&",
            "a",
            "b",
            "c",
            r"\end{array}",
        ],
    ),
    ("issue #60", r"\mathrm{...}", [r"\mathrm", "{", ".", ".", ".", "}"]),
    (
        "issue #61",
        r"\frac{x + 4}{x + \frac{123 \left(\sqrt{x} + 5\right)}{x + 4} - 8}",
        [
            r"\frac",
            "{",
            "x",
            "+",
            "4",
            "}",
            "{",
            "x",
            "+",
            r"\frac",
            "{",
            "123",
            r"\left",
            "(",
            r"\sqrt",
            "{",
            "x",
            "}",
            "+",
            "5",
            r"\right",
            ")",
            "}",
            "{",
            "x",
            "+",
            "4",
            "}",
            "-",
            "8",
            "}",
        ],
    ),
    (
        "issue #63",
        r"\sqrt {\sqrt {\left( x^{3}\right) + v}}",
        [
            r"\sqrt",
            "{",
            r"\sqrt",
            "{",
            r"\left",
            "(",
            "x",
            "^",
            "{",
            "3",
            "}",
            r"\right",
            ")",
            "+",
            "v",
            "}",
            "}",
        ],
    ),
    (
        "issue #77",
        r"\left[\begin{matrix}1 & 0 & 0 & 0\\0 & 1 & 0 & 0\\0 & 0 & 1 & 0\\0 & 0 & 0 & 1\end{matrix}\right]",
        [
            r"\left",
            "[",
            r"\begin{matrix}",
            "1",
            "&",
            "0",
            "&",
            "0",
            "&",
            "0",
            r"\\",
            "0",
            "&",
            "1",
            "&",
            "0",
            "&",
            "0",
            r"\\",
            "0",
            "&",
            "0",
            "&",
            "1",
            "&",
            "0",
            r"\\",
            "0",
            "&",
            "0",
            "&",
            "0",
            "&",
            "1",
            r"\end{matrix}",
            r"\right",
            "]",
        ],
    ),
    (
        "issue #78",
        r"x^{x^{x^{x}}} \left(x^{x^{x}} \left(x^{x} \left(\log{\left(x \right)} + 1\right) \log{\left(x \right)} + "
        r"\frac{x^{x}}{x}\right) \log{\left(x \right)} + \frac{x^{x^{x}}}{x}\right)",
        [
            "x",
            "^",
            "{",
            "x",
            "^",
            "{",
            "x",
            "^",
            "{",
            "x",
            "}",
            "}",
            "}",
            r"\left",
            "(",
            "x",
            "^",
            "{",
            "x",
            "^",
            "{",
            "x",
            "}",
            "}",
            r"\left",
            "(",
            "x",
            "^",
            "{",
            "x",
            "}",
            r"\left",
            "(",
            r"\log",
            "{",
            r"\left",
            "(",
            "x",
            r"\right",
            ")",
            "}",
            "+",
            "1",
            r"\right",
            ")",
            r"\log",
            "{",
            r"\left",
            "(",
            "x",
            r"\right",
            ")",
            "}",
            "+",
            r"\frac",
            "{",
            "x",
            "^",
            "{",
            "x",
            "}",
            "}",
            "{",
            "x",
            "}",
            r"\right",
            ")",
            r"\log",
            "{",
            r"\left",
            "(",
            "x",
            r"\right",
            ")",
            "}",
            "+",
            r"\frac",
            "{",
            "x",
            "^",
            "{",
            "x",
            "^",
            "{",
            "x",
            "}",
            "}",
            "}",
            "{",
            "x",
            "}",
            r"\right",
            ")",
        ],
    ),
    (
        "max",
        r"\max_{x \in \[a,b\]}f(x)",
        [
            r"\max",
            "_",
            "{",
            "x",
            r"\in",
            r"\[",
            "a",
            ",",
            "b",
            r"\]",
            "}",
            "f",
            "(",
            "x",
            ")",
        ],
    ),
]


@pytest.mark.parametrize(
    "name, latex, expected", ids=[x[0] for x in PARAMS], argvalues=PARAMS,
)
def test_tokenize(name: str, latex: str, expected: list):
    assert list(tokenize(latex)) == expected
