import pytest

from latex2mathml.converter import convert, convert_to_element
from latex2mathml.exceptions import DoubleSubscriptsError, DoubleSuperscriptsError


@pytest.mark.parametrize(
    "latex",
    [
        pytest.param("x", id="single-identifier"),
        pytest.param("xyz", id="multiple-identifier"),
        pytest.param("3", id="single-number"),
        pytest.param("333", id="multiple-numbers"),
        pytest.param("12.34", id="decimal-numbers"),
        pytest.param("12x", id="numbers-and-identifiers"),
        pytest.param("+", id="single-operator"),
        pytest.param("3-2", id="numbers-and-operators"),
        pytest.param(r"3 \times 2", id="numbers-and-operators-times"),
        pytest.param(r"3 \cdot 2", id="numbers-and-operators-cdot"),
        pytest.param(r"3 \div 2", id="numbers-and-operators-div"),
        pytest.param("3x*2", id="numbers-identifiers-and-operators"),
        pytest.param("{a}", id="single-group"),
        pytest.param("{a}{b}", id="multiple-groups"),
        pytest.param("{a+{b}}", id="inner-group"),
        pytest.param(r"1 \over 2", id="over"),
        pytest.param(r"{1 \over 2}", id="over-inside-braces"),
        pytest.param(r"\begin{matrix}a_{1} & b_{2} \\ c_{3} & d_{4} \end{matrix}", id="complex-matrix"),
        pytest.param(
            r"\left\{ \begin{array} { l } { 3x - 5y + 4z = 0} \\ { x - y + 8z = 0} \\ { 2x - 6y + z = 0} \end{array} "
            r"\right.",
            id="null-delimiter",
        ),
        pytest.param("a_b", id="subscript"),
        pytest.param("a^b", id="superscript"),
        pytest.param("a_b^c", id="subscript-and-superscript"),
        pytest.param("a^b_c", id="superscript-and-subscript"),
        pytest.param("{a_b}", id="subscript-within-curly-braces"),
        pytest.param("{a^b}", id="superscript-within-curly-braces"),
        pytest.param("a^{i+1}_3", id="superscript-subscript-and-curly-braces"),
        pytest.param(r"\frac{1}{2}", id="simple-fraction"),
        pytest.param(r"\sqrt{2}", id="square-root"),
        pytest.param(r"\sqrt[3]{2}", id="root"),
        pytest.param(r"\binom{2}{3}", id="binomial"),
        pytest.param(r"\left(x\right)", id="left-and-right"),
        pytest.param(r"\,", id="space"),
        pytest.param(r"\begin{matrix}a & b \\ c & d \end{matrix}", id="matrix"),
        pytest.param(r"\matrix{a & b \\ c & d}", id="matrix-without-begin-and-end"),
        pytest.param(r"\begin{matrix*}[r]a & b \\ c & d \end{matrix*}", id="matrix-with-alignment"),
        pytest.param(r"\begin{matrix}-a & b \\ c & d \end{matrix}", id="matrix-with-negative-sign"),
        pytest.param(r"\begin{pmatrix}a & b \\ c & d \end{pmatrix}", id="pmatrix"),
        pytest.param(r"\begin{array}{cr} 1 & 2 \\ 3 & 4 \end{array}", id="simple-array"),
        pytest.param(r"\begin{array}{c|rl} 1 & 2 & 3 \\ 4 & 5 & 6 \end{array}", id="array-with-vertical-bar"),
        pytest.param(
            r"\begin{array}{cr} 1 & 2 \\ 3 & 4 \\ \hline 5 & 6 \\ \hdashline 7 & 8 \end{array}",
            id="array-with-horizontal-lines",
        ),
        pytest.param(
            r"""\begin{bmatrix}
             a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
             a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
             \vdots  & \vdots  & \ddots & \vdots  \\
             a_{m,1} & a_{m,2} & \cdots & a_{m,n}
            \end{bmatrix}""",
            id="issue-33",
        ),
        pytest.param(r"\sqrt { ( - 25 ) ^ { 2 } } = \pm 25", id="issue-42"),
        pytest.param("2 < 5", id="issue-45-lt"),
        pytest.param("2 > 5", id="issue-45-gt"),
        pytest.param(r"\And", id="And"),
        pytest.param(r"\left(- x^{3} + 5\right)^{5}", id="issue-44"),
        pytest.param(r"\mathbb{R}", id="issue-51"),
        pytest.param(r"\bar{z_1} = z_2", id="issue-52"),
        pytest.param(r"\mathrm{...}", id="issue-60-1"),
        pytest.param(r"\mathrm{...}+\mathrm{...}", id="issue-60-2"),
        pytest.param(r"\frac{x + 4}{x + \frac{123 \left(\sqrt{x} + 5\right)}{x + 4} - 8}", id="issue-61"),
        pytest.param(r"\sqrt {\sqrt {\left( x^{3}\right) + v}}", id="issue-63"),
        pytest.param(r"1_{}", id="empty-subscript"),
        pytest.param(r"\begin{Bmatrix}\end{Bmatrix}", id="Bmatrix"),
        pytest.param(r"\begin{vmatrix}\end{vmatrix}", id="vmatrix"),
        pytest.param(r"\begin{Vmatrix}\end{Vmatrix}", id="upper-Vmatrix"),
        pytest.param(r"\begin{matrix}1^2\end{matrix}", id="command-inside-matrix"),
        pytest.param(r"\e", id="backslash-e"),
        pytest.param(
            r"\left[\begin{matrix}1 & 0 & 0 & 0\\0 & 1 & 0 & 0\\0 & 0 & 1 & 0\\0 & 0 & 0 & 1\end{matrix}\right]",
            id="issue-77",
        ),
        pytest.param(r"\log{x}", id="logarithm"),
        pytest.param(r"\log_2{x}", id="logarithm-with-base"),
        pytest.param("^3", id="exponent-without-base-works"),
        pytest.param(r"\lim_{x \to +\infty} f(x)", id="limit-at-plus-infinity"),
        pytest.param(r"\inf_{x > s}f(x)", id="inf"),
        pytest.param(r"\int\limits_{0}^{\pi}", id="issue-76"),
        pytest.param(r"\int\limits^{\pi}_{0}", id="issue-301-a"),
        pytest.param(r"\int\limits_{\pi}", id="issue-301-b"),
        pytest.param(r"\int\limits^{\pi}", id="issue-301-c"),
        pytest.param(r"\substack{ \xi{2}=g{\left(x \right)}}", id="issue-75-1-row"),
        pytest.param(r"\sum_{\substack{1\le i\le n\\ i\ne j}}", id="issue-75-2-rows"),
        pytest.param(
            r"\tan x+\sec x+\cos x+\sin x+\cot x+\csc x+\arccos x+\arcsin x+\arctan x +\cosh x+\coth x+\sinh x+\tanh x",
            id="issue-91",
        ),
        pytest.param(r"p_{\max}", id="issue-98"),
        pytest.param(r"\vec{AB}", id="issue-103"),
        pytest.param(r"\begin{cases} {x=1} \\ {y=-2}\end{cases}", id="issue-106"),
        pytest.param(r"\max f", id="issue-108-1"),
        pytest.param(r"\max \{a, b, c\}", id="issue-108-2"),
        pytest.param(r"\min{(x, y)}", id="issue-108-3"),
        pytest.param(r"\dot A", id="issue-112-1"),
        pytest.param(r"\dot{A}", id="issue-112-2"),
        pytest.param(r"\operatorname{sn}x", id="issue-109-1"),
        pytest.param(r"\operatorname{sn}(x+y)", id="issue-109-2"),
        pytest.param(r"\text{Let}\ x=\text{number of cats}.", id="issue-118"),
        pytest.param(r"F(a,n)=\overset{a-a-a\cdots-a}{}ntext{个}a", id="issue-125-1-overset"),
        pytest.param(r"a\,\overset{?}{=}\,b", id="issue-125-2-overset"),
        pytest.param(r"\underset ab", id="issue-125-3-underset"),
        pytest.param(r"a\mathop{t}b\mathop{t}c", id="issue-125-4-mathop"),
        pytest.param(r"\mathop{x}\limits_0^1", id="issue-125-4-limits"),
        pytest.param(r"\Bigg[\bigg[\Big[\big[[", id="big"),
        pytest.param(r"x\rm {\text{var} = 1+\{b\}}\sf \Delta", id="global-fonts"),
        pytest.param("f'(x) = 2x, f''(x) = 2", id="prime"),
        pytest.param("f'''(x)", id="issue-462-triple-prime"),
        pytest.param("f''''(x)", id="issue-462-quadruple-prime"),
        pytest.param("f'''''(x)", id="issue-462-quintuple-prime"),
        pytest.param("f''''''''(x)", id="issue-462-octuple-prime"),
        pytest.param("'x", id="prime-no-base"),
        pytest.param(
            r"""|\,|\:|\>|\;|\\|\!|\quad|\qquad|\hspace1em|\hspace{10ex}|\enspace|\hskip1em|\kern-1.5pt|\mkern10mu|
            \mskip18mu|\mspace18mu|\negthinspace|\negmedspace|\negthickspace|\nobreakspace|\space|\thinspace|""",
            id="spaces",
        ),
        pytest.param(r"|x|", id="pipe"),
        pytest.param(r"\|x\|", id="double-pipe"),
        pytest.param("Hello~World", id="tilde"),
        pytest.param(r"\text{ Hello~World }", id="tilde-and-space-in-text"),
        pytest.param(
            r"""% this is hidden
            100\%!% this is hidden, too""",
            id="comments",
        ),
        pytest.param(r"\#\$\%\&\_\{\}", id="escaped-characters"),
        pytest.param(r"{a \above 1pt b} + {c \above {1.5pt} d}", id="above"),
        pytest.param(r"\acute a \acute{bc}", id="acute"),
        pytest.param(r"a \atop {b \atopwithdelims | \} c}", id="atop-and-atopwithdelims"),
        pytest.param(r"{a \abovewithdelims [ ] 1pt b} + {c \abovewithdelims . . {1.5pt} d}", id="abovewithdelims"),
        pytest.param(r"\Bbb {\text{var} = 1+\{b\}}", id="blackboard-bold"),
        pytest.param(r"\Bbb{AB}C", id="Bbb-group"),
        pytest.param(r"\bigcirc", id="bigcirc"),
        pytest.param(r"\boldsymbol {\text{var} = 1+\{b\}}", id="boldsymbol"),
        pytest.param(r"\boxed \Box", id="boxed-box"),
        pytest.param(r"\breve a \breve{bc}", id="breve"),
        pytest.param(r"{\brace} + {a \brace b}", id="brace"),
        pytest.param(r"{\brack} + {a \brack b}", id="brace-1"),
        pytest.param(r"{\cal {\text{var} = 1+\{b\}}} + B", id="calligraphic-mode"),
        pytest.param(r"a\centerdot b", id="centerdot"),
        pytest.param(r"\cfrac{2}{1+ \cfrac{2}{1}}", id="cfrac"),
        pytest.param(r"\check a \check{bc}", id="check"),
        pytest.param(r"a \choose b", id="choose"),
        pytest.param(r"\circledS", id="circledS"),
        pytest.param(r"{a\color{red}bc}d", id="color"),
        pytest.param(r"\color{}ab", id="empty-color-works"),
        pytest.param(r"\dbinom a b", id="binomial-coefficients"),
        pytest.param(r"\ddot a \dddot b \ddddot c", id="ddot-dddot-ddddot"),
        pytest.param(r"\deg(f(x))", id="degree-polynomial"),
        pytest.param(r"\det(A)", id="determinant"),
        pytest.param(r"\dim(A)", id="dimension-vector-space"),
        pytest.param(r"\dfrac a b", id="dfrac"),
        pytest.param(r"\diagdown \diagup", id="diagdown-diagup"),
        pytest.param(r"x_1, \dots, x_n", id="dots"),
        pytest.param(r"x_1 + \dotsb + x_n", id="dotsb"),
        pytest.param(r"x_1, \dotsc, x_n", id="dotsc"),
        pytest.param(r"A_1 \dotsi A_n", id="dotsi"),
        pytest.param(r"x_1 \dotsm x_n", id="dotsm"),
        pytest.param(r"A_1 \dotso A_n", id="dotso"),
        pytest.param(r"\frac ab + {\displaystyle \frac cd + \frac ef} + \frac gh", id="displaystyle"),
        pytest.param(
            r"\frac ab+\displaystyle\frac cd+\textstyle\frac ef+\scriptstyle\frac gh+\scriptscriptstyle\frac ij",
            id="styles",
        ),
        pytest.param(
            r"""
            \displaylines{
                a = a\cr
                \text{if } a=b \text{ then } b=a\\
                \text{if } a=b \text{ and } b=c \text{ then } a=c
            }
            """,
            id="displaylines",
        ),
        pytest.param(r"\emptyset", id="emptyset"),
        pytest.param(r"\exp x", id="exponential-function"),
        pytest.param(r"\fbox{ Hello! }", id="fbox"),
        pytest.param(r"{\frak {\text{var} = 1+\{b\}}} + B", id="fraktur"),
        pytest.param(r"\gcd_{\rm sub}^{\rm sup}", id="greatest-common-divisor"),
        pytest.param(r"\genfrac\{]{1pt}{0}{a+b}{c+d}", id="genfrac-displaystyle"),
        pytest.param(r"\genfrac(|{1pt}{1}{a+b}{c+d}", id="genfrac-textstyle"),
        pytest.param(r"\genfrac(.{1pt}{2}{a+b}{c+d}", id="genfrac-scriptstyle"),
        pytest.param(r"\genfrac\{\}{1pt}{3}{a+b}{c+d}", id="genfrac-scriptscriptstyle"),
        pytest.param(r"\gggtr", id="gggtr"),
        pytest.param(r"\gvertneqq", id="gvertneqq"),
        pytest.param(r"\gt", id="gt"),
        pytest.param(r"\grave a \grave{bc}", id="grave"),
        pytest.param(r"\hat a \hat{bc}", id="hat"),
        pytest.param(r"\hom", id="hom"),
        pytest.param(r"\href{https://github.com/roniemartinez/latex2mathml}{\text{latex2mathml}}", id="href"),
        pytest.param(r"[{[\Huge[\huge[[}[", id="huge"),
        pytest.param(r"\sqrt[abc]{123}", id="sqrt-with-multiple-root-nodes"),
        pytest.param(
            r"\begin{array}{l} \text{Side Angle Side}\\ \text{S}\hphantom{\text{ide }}\text{A}\hphantom{\text{ngle }}"
            r"\text{S} \end{array}",
            id="hphantom",
        ),
        pytest.param(r"\idotsint", id="idotsint"),
        pytest.param(r"\intop", id="intop"),
        pytest.param(r"\injlim", id="injlim"),
        pytest.param(r"\ker", id="ker"),
        pytest.param(r"[{[\LARGE[\Large[\large[[}[", id="large"),
        pytest.param(r"[{[\normalsize[\scriptsize[[}[", id="normalsize-scriptsize"),
        pytest.param(r"\mathbb{AB}C", id="mathbb"),
        pytest.param(r"\mathbf {\text{var} = 1+\{b\}}", id="mathbf"),
        pytest.param(r"{\mathcal {\text{var} = 1+\{b\}}} + B", id="mathcal"),
        pytest.param(r"{\mathfrak {\text{var} = 1+\{b\}}} + B", id="mathfrak"),
        pytest.param(r"{\mathit {\text{var} = 1+\{b\}}} + B", id="mathit"),
        pytest.param(r"{\mathrm {\text{var} = 1+\{b\}}} + B", id="mathrm"),
        pytest.param(r"{\mathscr {\text{var} = 1+\{b\}}} + B", id="mathscr"),
        pytest.param(r"{\mathsf {\text{var} = 1+\{b\}}} + B", id="mathsf"),
        pytest.param(r"{\mathtt {\text{var} = 1+\{b\}}} + B", id="mathtt"),
        pytest.param(
            r"\mathop{a}\mathord{b}\mathpunct{c}\mathbin{d}\mathrel{e}", id="math-commands-that-currently-does-nothing"
        ),
        pytest.param(r"\hbox{This is a sentence.}", id="hbox"),
        pytest.param(r"\hbox{left $x > 0$ center \$x > 0\$ right}", id="hbox-with-math-mode"),
        pytest.param(r"\hbox{\alpha $\alpha$}", id="hbox-with-backslash-in-text"),
        pytest.param(r"\begin{matrix} xxxxxx & xxxxxx & xxxxxx \cr ab & \hfil ab & ab\hfil\cr \end{matrix}", id="hfil"),
        pytest.param(r"\ldotp", id="ldotp"),
        pytest.param(r"\lg", id="lg"),
        pytest.param(r"\liminf", id="liminf"),
        pytest.param(r"\limsup", id="limsup"),
        pytest.param(r"\llless", id="llless"),
        pytest.param(r"\lt", id="lt"),
        pytest.param(r"\lvert", id="lvert"),
        pytest.param(r"\lVert", id="lVert-double"),
        pytest.param(r"\lvertneqq", id="lvertneqq"),
        pytest.param(r"\ngeqq", id="ngeqq"),
        pytest.param(r"\nshortmid", id="nshortmid"),
        pytest.param(r"\nshortparallel", id="nshortparallel"),
        pytest.param(r"\nsubseteqq", id="nsubseteqq"),
        pytest.param(r"\omicron", id="omicron"),
        pytest.param(r"\Pr", id="Pr"),
        pytest.param(r"\projlim", id="projlim"),
        pytest.param(r"\rvert", id="rvert"),
        pytest.param(r"\rVert", id="rVert-double"),
        pytest.param(r"\S", id="S"),
        pytest.param(r"\shortmid", id="shortmid"),
        pytest.param(r"\smallfrown", id="smallfrown"),
        pytest.param(r"\smallint", id="smallint"),
        pytest.param(r"\smallsmile", id="smallsmile"),
        pytest.param(r"\surd", id="surd"),
        pytest.param(r"\thicksim", id="thicksim"),
        pytest.param(r"\thickapprox", id="thickapprox"),
        pytest.param(r"\varsubsetneqq", id="varsubsetneqq"),
        pytest.param(r"\varsupsetneq", id="varsupsetneq"),
        pytest.param(r"\varsupsetneqq", id="varsupsetneqq"),
        pytest.param(r"[{[\small[\tiny[\Tiny[[}[", id="small-tiny"),
        pytest.param(r"\mbox{This is a sentence.}", id="mbox"),
        pytest.param(r"\frac{\style{color:red}{x+1}}{\style{color:green}y+2}", id="style"),
        pytest.param(r"\mathring a \mathring{bc}", id="mathring"),
        pytest.param(r"\overleftarrow a \overleftarrow{bc}", id="overleftarrow"),
        pytest.param(r"\overleftrightarrow a \overleftrightarrow{bc}", id="overleftrightarrow"),
        pytest.param(r"\overline a \overline{bc}", id="overline"),
        pytest.param(r"\overparen a \overparen{bc}", id="overparen"),
        pytest.param(r"\overrightarrow a \overrightarrow{bc}", id="overrightarrow"),
        pytest.param(r"\tilde a \tilde{bc}", id="tilde-1"),
        pytest.param(r"\underleftarrow a \underleftarrow{bc}", id="underleftarrow"),
        pytest.param(r"\underrightarrow a \underrightarrow{bc}", id="underrightarrow"),
        pytest.param(r"\underleftrightarrow a \underleftrightarrow{bc}", id="underleftrightarrow"),
        pytest.param(r"\underline a \underline{bc}", id="underline"),
        pytest.param(r"\underparen a \underparen{bc}", id="underparen"),
        pytest.param(r"\widehat a \widehat{bc}", id="widehat"),
        pytest.param(r"\widetilde a \widetilde{bc}", id="widetilde"),
        pytest.param(r"\phantom a", id="phantom"),
        pytest.param(r"\vphantom a", id="vphantom"),
        pytest.param(r"\sideset{_1^2}{_3^4}\sum", id="sideset"),
        pytest.param(r"\sideset{_1^2}{_3^4}{\sum}", id="307-a"),
        pytest.param(r"\sideset{^{°}}{}{C}", id="307-b"),
        pytest.param(r"\tbinom{2}{3}", id="tbinom"),
        pytest.param(r"\tfrac{1}{2}", id="tfrac"),
        pytest.param(r"{\mit {\text{var} = 1+\{b\}}} + B", id="mit"),
        pytest.param(r"{\oldstyle {\text{var} = 1+\{b\}}} + B", id="oldstyle"),
        pytest.param(r"{\scr {\text{var} = 1+\{b\}}} + B", id="scr"),
        pytest.param(r"{\tt {\text{var} = 1+\{b\}}} + B", id="tt"),
        pytest.param(r"\textbf{ Hello~World }", id="textbf"),
        pytest.param(r"\textit{ Hello~World }", id="textit"),
        pytest.param(r"\textrm{ Hello~World }", id="textrm"),
        pytest.param(r"\textsf{ Hello~World }", id="textsf"),
        pytest.param(r"\texttt{ Hello~World }", id="texttt"),
        pytest.param(r"\LaTeX", id="LaTeX"),
        pytest.param(r"\Bbb \LaTeX", id="LaTeX-with-style"),
        pytest.param(r"\TeX", id="TeX"),
        pytest.param(r"\rm \TeX", id="TeX-with-style"),
        pytest.param(r"\skew7\hat A", id="skew"),
        pytest.param(r"\skew{8}\tilde M", id="skew-with-braces"),
        pytest.param(r"\mod 5", id="mod"),
        pytest.param(r"\pmod 5", id="pmod"),
        pytest.param(r"\left\{\middle|\right\}", id="middle"),
        pytest.param(r"9 \bmod2", id="bmod"),
        pytest.param(r"\overbrace3", id="overbrace-a"),
        pytest.param(r"\overbrace3^a", id="overbrace-b"),
        pytest.param(r"\overbrace3^a_x", id="overbrace-c"),
        pytest.param(r"\underbrace3", id="underbrace-a"),
        pytest.param(r"\underbrace3_a", id="underbrace-b"),
        pytest.param(r"\underbrace3_a^x", id="underbrace-c"),
        pytest.param(r"\xleftarrow x", id="xleftarrow"),
        pytest.param(r"\xleftarrow[y] x", id="xleftarrow-with-argument"),
        pytest.param(r"\xrightarrow x", id="xrightarrow"),
        pytest.param(r"\xrightarrow[y] x", id="xrightarrow-with-argument"),
        pytest.param(
            r"\bigl(\begin{smallmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ \end{smallmatrix}\bigr)", id="bigl-smallmatrix-bigr"
        ),
        pytest.param(r"\not\in\not a\not\operatorname{R}\not", id="not"),
        pytest.param(r"\begin{split}  x &= y \\  &=z  \end{split}", id="split"),
        pytest.param(r"\begin{align*}x &=y & w &=z  & a&=b \end{align*}", id="align"),
        pytest.param(r"\sum_{0}^{\pi}", id="issue-498-sum"),
        pytest.param(r"\prod_{0}^{\pi}", id="issue-498-prod"),
        pytest.param(r"\arctg x", id="arctg"),
        pytest.param(r"\argmax_{x}", id="argmax"),
        pytest.param(r"\varinjlim", id="varinjlim"),
        pytest.param(r"\sum\nolimits_{i=0}^{n}", id="nolimits"),
        pytest.param(r"\bold{x}", id="bold"),
        pytest.param(r"\bm{x}", id="bm"),
        pytest.param(r"\mathsfit{x}", id="mathsfit"),
        pytest.param(r"\emph{ Hello }", id="emph"),
        pytest.param(r"\footnotesize x", id="footnotesize"),
        pytest.param(r"\thickspace", id="thickspace"),
        pytest.param(r"\stackrel{f}{\to}", id="stackrel"),
        pytest.param(r"90\degree", id="degree"),
        pytest.param(r"\cancel{x}", id="cancel"),
        pytest.param(r"\llap{x}", id="llap"),
        pytest.param(r"\mathllap{x}", id="mathllap"),
        pytest.param(r"\overbracket{x}", id="overbracket"),
        pytest.param(r"\widecheck{x}", id="widecheck"),
        pytest.param(r"\xLeftarrow[y] x", id="xLeftarrow-double"),
        pytest.param(r"\xleftrightarrow{x}", id="xleftrightarrow"),
        pytest.param(r"\xhookleftarrow{x}", id="xhookleftarrow"),
        pytest.param(r"\operatornamewithlimits{lim}_{x}", id="operatornamewithlimits"),
        pytest.param(r"\pod{a}", id="pod"),
        pytest.param(r"\textcolor{red}{x+y}", id="textcolor"),
        pytest.param(r"\colorbox{yellow}{x+y}", id="colorbox"),
        pytest.param(r"\fcolorbox{red}{yellow}{x+y}", id="fcolorbox"),
        pytest.param(r"\smash{x}", id="smash"),
        pytest.param(r"\smash[b]{x}", id="smash-bottom"),
        pytest.param(r"\rule{1em}{2em}", id="rule"),
        pytest.param(r"\bra{\psi}", id="bra"),
        pytest.param(r"\ket{\psi}", id="ket"),
        pytest.param(r"\braket{\phi|\psi}", id="braket"),
        pytest.param(r"\mathstrut", id="mathstrut"),
        pytest.param(r"\operatorname*{argmax}_{x}", id="operatorname-star"),
        pytest.param(r"\vcenter{x}", id="vcenter"),
        pytest.param(r"\mathbin{+}", id="mathbin"),
        pytest.param(r"\mathop{x}", id="mathop"),
        pytest.param(r"\mathord{x}", id="mathord"),
        pytest.param(r"\mathrel{=}", id="mathrel"),
        pytest.param(r"\unicode{x263A}", id="unicode"),
        pytest.param(r"\verb|hello world|", id="verb"),
        pytest.param(r"x^2 \tag{1}", id="tag"),
        pytest.param(r"x^2 \tag*{A}", id="tag-star"),
        pytest.param(r"\class{my-class}{x+y}", id="class"),
        pytest.param(r"\shoveleft{x}", id="shoveleft"),
        pytest.param(r"\raise{3pt}{x}", id="raise"),
        pytest.param(r"\lower{3pt}{x}", id="lower"),
        pytest.param(r"\mathchoice{D}{T}{S}{SS}", id="mathchoice-block"),
        pytest.param(r"\sqrt[\leftroot{2}\uproot{4} 3]{x}", id="leftroot-uproot"),
        pytest.param(r"\eqalign{a &= b \cr c &= d}", id="eqalign"),
    ],
)
def test_converter(snapshot: str, latex: str) -> None:
    assert convert(latex, display="block") == snapshot


@pytest.mark.parametrize(
    "latex",
    [
        pytest.param(r"\sum_{0}^{\pi}", id="issue-498-sum"),
        pytest.param(r"\prod_{0}^{\pi}", id="issue-498-prod"),
        pytest.param(r"\sum_{\substack{1\le i\le n\\ i\ne j}}", id="issue-75-2-rows"),
        pytest.param(r"\mathchoice{D}{T}{S}{SS}", id="mathchoice-inline"),
    ],
)
def test_converter_inline(snapshot: str, latex: str) -> None:
    assert convert(latex) == snapshot


@pytest.mark.parametrize(
    "latex",
    [
        "f^a^b",
        "f''^2",
    ],
)
def test_double_superscripts_raises(latex: str) -> None:
    with pytest.raises(DoubleSuperscriptsError):
        convert(latex)


def test_double_subscripts_raises() -> None:
    with pytest.raises(DoubleSubscriptsError):
        convert("f_a_b")


@pytest.mark.parametrize(
    "latex, expected_inner",
    [
        (
            r"\hat{x}",
            '<mover accent="true"><mrow><mi>x</mi></mrow><mo>&#x0005E;</mo></mover>',
        ),
        (
            r"\hat{abc}",
            '<mover accent="true"><mrow><mi>a</mi><mi>b</mi><mi>c</mi></mrow><mo>&#x0005E;</mo></mover>',
        ),
    ],
)
def test_issue_543_hat_is_accent(latex: str, expected_inner: str) -> None:
    expected = f'<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow>{expected_inner}</mrow></math>'
    assert convert(latex, display="block") == expected


def test_convert_to_element(snapshot: str) -> None:
    from xml.etree.ElementTree import tostring

    element = convert_to_element("1")
    assert tostring(element, encoding="unicode") == snapshot


def test_convert_to_element_with_parent(snapshot: str) -> None:
    from xml.etree.ElementTree import Element, tostring

    parent = Element("div")
    convert_to_element("1", parent=parent)
    assert tostring(parent, encoding="unicode") == snapshot
